[package]
name = "RustOps"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.0.3"
ndarray = {version = "0.15", features = ["rayon"] }
num-traits = "0.2"
ndarray-npy = "0.8.1"
thiserror = "2.0.12"
ndarray-linalg = "0.17"
ndarray_einsum_beta = "0.7.0"
clap = { version = "4.2", features = ["derive"] }
image = "0.25"
anyhow = "1.0"
ndarray-rand = "0.14"
rand = "0.8"

[dev-dependencies]
approx = "0.4"
num-traits = "0.2"