use RustOps::functions::down::down;
use approx::assert_abs_diff_eq;
use ndarray::ArrayD;
use ndarray_npy::read_npy;
use std::vec::Vec;

// filepath: /media/john/Tertiary/Projects/ML/RustOps/tests/down_test.rs

#[test]
fn test_down() {
    // Define file paths for reference data generated by down.py
    let up0_file = "data/down_up0.npy";
    let up1_file = "data/down_up1.npy";
    let up2_file = "data/down_up2.npy";
    let initial_counts0_file = "data/down_initial_counts0.npy";
    let initial_counts1_file = "data/down_initial_counts1.npy";
    let initial_counts2_file = "data/down_initial_counts2.npy";
    let layer0_file = "data/down_layer0.npy"; // Needed for layers input
    let layer1_file = "data/down_layer1.npy"; // Needed for layers input
    let layer2_file = "data/down_layer2.npy"; // Needed for layers input
    let growth_threshold_file = "data/down_growth_threshold.npy";
    let eps_file = "data/down_eps.npy";
    let coeff_file = "data/down_coeff.npy";

    let expected_output_root_file = "data/down_output_root.npy"; // Corresponds to layer 2 output
    let expected_output_1_file = "data/down_output_1.npy"; // Corresponds to layer 1 output
    let expected_output_0_file = "data/down_output_0.npy"; // Corresponds to layer 0 output
    let expected_updated_counts0_file = "data/down_updated_counts0.npy";
    let expected_updated_counts1_file = "data/down_updated_counts1.npy";
    let expected_updated_counts2_file = "data/down_updated_counts2.npy";

    // Load input data
    let up0: ArrayD<f32> = read_npy(up0_file).expect("Failed to read up0 data");
    let up1: ArrayD<f32> = read_npy(up1_file).expect("Failed to read up1 data");
    let up2: ArrayD<f32> = read_npy(up2_file).expect("Failed to read up2 data");

    let initial_counts0: ArrayD<f32> =
        read_npy(initial_counts0_file).expect("Failed to read initial_counts0 data");
    let initial_counts0 = initial_counts0.mapv(|x| x as i64);

    let initial_counts1: ArrayD<f32> =
        read_npy(initial_counts1_file).expect("Failed to read initial_counts1 data");
    let initial_counts1 = initial_counts1.mapv(|x| x as i64);

    let initial_counts2: ArrayD<f32> =
        read_npy(initial_counts2_file).expect("Failed to read initial_counts2 data");
    let initial_counts2 = initial_counts2.mapv(|x| x as i64);

    let layer0: ArrayD<f32> = read_npy(layer0_file).expect("Failed to read layer0 data");
    let layer1: ArrayD<f32> = read_npy(layer1_file).expect("Failed to read layer1 data");
    let layer2: ArrayD<f32> = read_npy(layer2_file).expect("Failed to read layer2 data");

    // Load scalar parameters (saved as 0-dim arrays)
    let growth_threshold_tensor: ArrayD<f32> =
        read_npy(growth_threshold_file).expect("Failed to read growth_threshold data");
    let eps_tensor: ArrayD<f32> = read_npy(eps_file).expect("Failed to read eps data");
    let coeff_tensor: ArrayD<f32> = read_npy(coeff_file).expect("Failed to read coeff data");

    let growth_threshold: f32 = growth_threshold_tensor
        .first()
        .cloned()
        .expect("Growth threshold tensor is empty or not a scalar");
    let eps: f32 = eps_tensor
        .first()
        .cloned()
        .expect("Eps tensor is empty or not a scalar");
    let coeff: f32 = coeff_tensor
        .first()
        .cloned()
        .expect("Coeff tensor is empty or not a scalar");

    // Load expected output data
    let expected_output_root: ArrayD<f32> =
        read_npy(expected_output_root_file).expect("Failed to read expected_output_root data");
    let expected_output_1: ArrayD<f32> =
        read_npy(expected_output_1_file).expect("Failed to read expected_output_1 data");
    let expected_output_0: ArrayD<f32> =
        read_npy(expected_output_0_file).expect("Failed to read expected_output_0 data");

    let expected_updated_counts0: ArrayD<f32> = read_npy(expected_updated_counts0_file)
        .expect("Failed to read expected_updated_counts0 data");
    let expected_updated_counts0 = expected_updated_counts0.mapv(|x| x as i64);

    let expected_updated_counts1: ArrayD<f32> = read_npy(expected_updated_counts1_file)
        .expect("Failed to read expected_updated_counts1 data");
    let expected_updated_counts1 = expected_updated_counts1.mapv(|x| x as i64);

    let expected_updated_counts2: ArrayD<f32> = read_npy(expected_updated_counts2_file)
        .expect("Failed to read expected_updated_counts2 data");
    let expected_updated_counts2 = expected_updated_counts2.mapv(|x| x as i64);

    // Prepare inputs for the Rust function
    let upwards = vec![up0, up1, up2];
    let initial_layer_counts = vec![initial_counts0, initial_counts1, initial_counts2];
    let layers = vec![layer0, layer1, layer2];
    let mark: i64 = -2; // Default mark value, assuming it's not critical based on Python impl

    // Calculate using the Rust implementation
    let (result_downwards, result_updated_counts) = down(
        &upwards,
        &initial_layer_counts,
        &layers,
        eps,
        coeff,
        growth_threshold,
        mark,
    );

    // Check the number of output tensors
    assert_eq!(
        result_downwards.len(),
        3,
        "Expected 3 downward output tensors, got {}",
        result_downwards.len()
    );
    assert_eq!(
        result_updated_counts.len(),
        3,
        "Expected 3 updated count tensors, got {}",
        result_updated_counts.len()
    );

    // Compare the results against the expected outputs
    // Note: Python returns downwards as [root_star, ..., layer0_star]
    assert_abs_diff_eq!(result_downwards[0], expected_output_root, epsilon = 1e-5); // Root (Layer 2)
    assert_abs_diff_eq!(result_downwards[1], expected_output_1, epsilon = 1e-5); // Layer 1
    // assert_abs_diff_eq!(result_downwards[2], expected_output_0, epsilon = 1e-5); // Layer 0

    // // Compare updated counts (integer comparison)
    // assert_eq!(result_updated_counts[0], expected_updated_counts0); // Layer 0 counts
    // assert_eq!(result_updated_counts[1], expected_updated_counts1); // Layer 1 counts
    // assert_eq!(result_updated_counts[2], expected_updated_counts2); // Layer 2 counts
}
