use RustOps::functions::hidden_forward_parallel;
use approx::assert_abs_diff_eq;
use ndarray::ArrayD;
use ndarray_npy::read_npy;

// filepath: /media/john/Tertiary/Projects/ML/RustOps/tests/hidden_forward_parallel_test.rs

#[test]
fn test_hidden_forward_parallel() {
    // Load reference data generated by the Python implementation
    let rho = 1e-8;
    let hidden_mm_file = "data/hidden_forward_parallel_hidden_mm_rho1e-08.npy";
    let children_x_file = "data/hidden_forward_parallel_children_x_rho1e-08.npy";
    let result_file = "data/hidden_forward_parallel_result_rho1e-08.npy";
    let propagation_file = "data/hidden_forward_parallel_propagation_rho1e-08.npy";
    let x_norm_file = "data/hidden_forward_parallel_x_norm_rho1e-08.npy";
    let norm_coeff_file = "data/hidden_forward_parallel_norm_coeff_rho1e-08.npy";
    let x_file = "data/hidden_forward_parallel_x_rho1e-08.npy";

    // Load input tensors
    let hidden_mm: ArrayD<f32> = read_npy(hidden_mm_file).unwrap();
    let children_x: ArrayD<f32> = read_npy(children_x_file).unwrap();

    // Load expected results
    let expected_result: ArrayD<f32> = read_npy(result_file).unwrap();

    // Calculate using the Rust implementation
    let result = hidden_forward_parallel::hidden_forward_parallel(hidden_mm, children_x, rho);

    // Compare the final result
    assert_abs_diff_eq!(result, expected_result, epsilon = 1e-5);
}
