use RustOps::functions::mark_reserved_indices;
use ndarray::{Array2, Array3, ArrayD};
use ndarray_npy::read_npy;

#[test]
fn test_mark_reserved_indices() {
    // Load reference data generated by Python
    let avail_file = "data/mark_reserved_indices_avail.npy";
    let all_file = "data/mark_reserved_indices_all.npy";
    let normal_file = "data/mark_reserved_indices_normal.npy";
    let counts_file = "data/mark_reserved_indices_counts.npy";
    let trigger_file = "data/mark_reserved_indices_trigger.npy";

    let avail_ref: ArrayD<i64> = read_npy(avail_file).unwrap();
    let all_ref: ArrayD<i64> = read_npy(all_file).unwrap();
    let normal_ref: ArrayD<f32> = read_npy(normal_file).unwrap();
    let counts_ref: ArrayD<f32> = read_npy(counts_file).unwrap();
    let trigger_ref: ArrayD<bool> = read_npy(trigger_file).unwrap();

    let (avail, sort_indices) =
        mark_reserved_indices::mark_reserved_indices(&normal_ref, &counts_ref, &trigger_ref, -2);

    // Compare results
    assert_eq!(avail, avail_ref);
    assert_eq!(sort_indices, all_ref);
}
