use RustOps::functions::mem_delta;
use approx::assert_abs_diff_eq;
use ndarray::ArrayD;
use ndarray_npy::read_npy;

#[test]
fn test_mem_delta() {
    // Load reference data generated by the Python implementation
    let parent_down_prop_file = "data/mem_delta_parent_down_prop.npy";
    let parent_mem_matrix_file = "data/mem_delta_parent_mem_matrix.npy";
    let child_down_prop_file = "data/mem_delta_child_down_prop.npy";
    let expected_delta_file = "data/mem_delta_delta.npy";

    // Load input tensors
    let parent_down_prop: ArrayD<f32> = read_npy(parent_down_prop_file).unwrap();
    let parent_mem_matrix: ArrayD<f32> = read_npy(parent_mem_matrix_file).unwrap();
    let child_down_prop: ArrayD<f32> = read_npy(child_down_prop_file).unwrap();

    // Load expected result
    let expected_delta: ArrayD<f32> = read_npy(expected_delta_file).unwrap();

    // Calculate using the Rust implementation
    let delta = mem_delta::mem_delta(parent_down_prop, parent_mem_matrix, child_down_prop);

    // Compare the result with expected output
    assert_abs_diff_eq!(delta, expected_delta, epsilon = 1e-5);
}
