use RustOps::functions::outer_up;
use approx::assert_abs_diff_eq;
use ndarray::ArrayD;
use ndarray_npy::read_npy;

#[test]
fn test_outer_up() {
    // Load reference data generated by the Python implementation
    let rho = 1e-8;
    let mems_file = "data/outer_up_mems_rho1e-08.npy";
    let xs_file = "data/outer_up_xs_rho1e-08.npy";
    let result_file = "data/outer_up_result_rho1e-08.npy";
    let h_sub_l_file = "data/outer_up_h_sub_l_rho1e-08.npy";

    let mems: ArrayD<f32> = read_npy(mems_file).unwrap();
    let xs: ArrayD<f32> = read_npy(xs_file).unwrap();
    let expected_result: ArrayD<f32> = read_npy(result_file).unwrap();
    let expected_h_sub_l: ArrayD<f32> = read_npy(h_sub_l_file).unwrap();

    // Extract the first memory tensor and create a vector with it
    let mems_vec = vec![mems];

    // Calculate using the Rust implementation
    let result = outer_up::outer_up(mems_vec, xs, rho);

    // Compare the result against both the expected result and h_sub_l
    // (which should be the same according to the Python implementation)
    assert_abs_diff_eq!(result, expected_result, epsilon = 1e-5);
    // assert_abs_diff_eq!(result, expected_h_sub_l, epsilon = 1e-5);
}
