use RustOps::functions::outer_forward_parallel;
use approx::assert_abs_diff_eq;
use ndarray::ArrayD;
use ndarray_npy::read_npy;

#[test]
fn test_outer_forward_parallel() {
    // Load reference data generated by the Python implementation
    let rho = 1e-8;
    let mems_file = "data/outer_forward_parallel_mems_rho1e-08.npy";
    let xs_file = "data/outer_forward_parallel_xs_rho1e-08.npy";
    let result_file = "data/outer_forward_parallel_result_rho1e-08.npy";
    let numerator_file = "data/outer_forward_parallel_numerator_rho1e-08.npy";
    let m_norm_file = "data/outer_forward_parallel_m_norm_rho1e-08.npy";
    let x_norm_file = "data/outer_forward_parallel_x_norm_rho1e-08.npy";
    let denom_file = "data/outer_forward_parallel_denom_rho1e-08.npy";

    let mems: ArrayD<f32> = read_npy(mems_file).unwrap();
    let xs: ArrayD<f32> = read_npy(xs_file).unwrap();
    let expected_result: ArrayD<f32> = read_npy(result_file).unwrap();
    let expected_numerator: ArrayD<f32> = read_npy(numerator_file).unwrap();
    let expected_m_norm: ArrayD<f32> = read_npy(m_norm_file).unwrap();
    let expected_x_norm: ArrayD<f32> = read_npy(x_norm_file).unwrap();
    let expected_denom: ArrayD<f32> = read_npy(denom_file).unwrap();

    // Calculate using the Rust implementation
    let result = outer_forward_parallel::outer_forward_parallel(mems, xs, rho);

    // Compare the final result and intermediate calculations
    assert_abs_diff_eq!(result, expected_result, epsilon = 1e-5);
}
