use RustOps::functions::pred;
use approx::assert_abs_diff_eq;
use ndarray::ArrayD;
use ndarray_npy::read_npy;

#[test]
fn test_pred() {
    // Load reference data generated by the Python implementation
    let parent_down_prop_file = "data/pred_parent_down_prop.npy";
    let parent_mem_matrix_file = "data/pred_parent_mem_matrix.npy";
    let prediction_file = "data/pred_prediction.npy";

    // Load input tensors
    let parent_down_prop: ArrayD<f32> = read_npy(parent_down_prop_file).unwrap();
    let parent_mem_matrix: ArrayD<f32> = read_npy(parent_mem_matrix_file).unwrap();

    // Load expected result
    let expected_prediction: ArrayD<f32> = read_npy(prediction_file).unwrap();

    // Calculate using the Rust implementation
    let prediction = pred::pred(parent_down_prop, parent_mem_matrix);

    // Compare the result with expected output
    assert_abs_diff_eq!(prediction, expected_prediction, epsilon = 1e-5);
}
