use RustOps::functions::up;
use approx::assert_abs_diff_eq;
use ndarray::ArrayD;
use ndarray_npy::read_npy;

// filepath: /media/john/Tertiary/Projects/ML/RustOps/tests/up_test.rs

#[test]
fn test_up() {
    // Load reference data generated by the Python implementation
    let rho = 1e-8;
    let layer0_file = "data/up_layer0.npy";
    let layer1_file = "data/up_layer1.npy";
    let layer2_file = "data/up_layer2.npy";
    let sensory_input_file = "data/up_sensory_input.npy";
    let expected_up0_file = "data/up_up0.npy";
    let expected_up1_file = "data/up_up1.npy";
    let expected_up2_file = "data/up_up2.npy";

    let layer0: ArrayD<f32> = read_npy(layer0_file).expect("Failed to read layer0 data");
    let layer1: ArrayD<f32> = read_npy(layer1_file).expect("Failed to read layer1 data");
    let layer2: ArrayD<f32> = read_npy(layer2_file).expect("Failed to read layer2 data");
    let sensory_input: ArrayD<f32> =
        read_npy(sensory_input_file).expect("Failed to read sensory input data");
    let expected_up0: ArrayD<f32> =
        read_npy(expected_up0_file).expect("Failed to read expected up0 data");
    let expected_up1: ArrayD<f32> =
        read_npy(expected_up1_file).expect("Failed to read expected up1 data");
    let expected_up2: ArrayD<f32> =
        read_npy(expected_up2_file).expect("Failed to read expected up2 data");

    // Prepare inputs for the Rust function
    let layers = vec![layer0, layer1, layer2];

    // Calculate using the Rust implementation
    // Note: The `up` function takes ownership of sensory_input, so no clone is needed here.
    // The layers vector is passed as a slice `&[ArrayD<f32>]`, so it's borrowed.
    let result_upwards = up::up(&layers, sensory_input, rho);

    // Check the number of output tensors
    assert_eq!(
        result_upwards.len(),
        3,
        "Expected 3 output tensors, got {}",
        result_upwards.len()
    );

    // Compare the results against the expected outputs
    assert_abs_diff_eq!(result_upwards[0], expected_up0, epsilon = 1e-5);
    assert_abs_diff_eq!(result_upwards[1], expected_up1, epsilon = 1e-5);
    assert_abs_diff_eq!(result_upwards[2], expected_up2, epsilon = 1e-5);
}
